Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,14 +12,17 @@ on:
           - us-east-1
           - us-west-1
           - us-west-2
-      create_vpc:
-        description: "Set to true to create a VPC"
+      terraform_action:
+        description: "Choose the Terraform action (apply, destroy_ec2, destroy_s3, destroy_autoscaling, destroy_all)"
         required: true
-        default: false
+        default: "apply"
         type: choice
         options:
-          - true
-          - false
+          - apply
+          - destroy_ec2
+          - destroy_s3
+          - destroy_autoscaling
+          - destroy_all
       create_ec2:
         description: "Set to true to create an EC2 instance"
         required: true
@@ -88,30 +91,38 @@ jobs:
     - name: Terraform Init
       run: terraform init
 
-    - name: Terraform Plan
+    - name: Terraform Apply or Destroy
       run: |
-        terraform plan \
-          -var="aws_region=${{ github.event.inputs.aws_region }}" \
-          -var="create_vpc=${{ github.event.inputs.create_vpc }}" \
-          -var="create_ec2=${{ github.event.inputs.create_ec2 }}" \
-          -var="create_s3=${{ github.event.inputs.create_s3 }}" \
-          -var="create_autoscaling=${{ github.event.inputs.create_autoscaling }}" \
-          -var="ami_id=${{ github.event.inputs.ami_id }}" \
-          -var="instance_type=${{ github.event.inputs.instance_type }}" \
-          -var="subnet_id=${{ github.event.inputs.subnet_id }}" \
-          -var="security_group_id=${{ github.event.inputs.security_group_id }}" \
-          -var="s3_bucket_name=${{ github.event.inputs.s3_bucket_name }}"
-
-    - name: Terraform Apply
-      run: |
-        terraform apply -auto-approve \
-          -var="aws_region=${{ github.event.inputs.aws_region }}" \
-          -var="create_vpc=${{ github.event.inputs.create_vpc }}" \
-          -var="create_ec2=${{ github.event.inputs.create_ec2 }}" \
-          -var="create_s3=${{ github.event.inputs.create_s3 }}" \
-          -var="create_autoscaling=${{ github.event.inputs.create_autoscaling }}" \
-          -var="ami_id=${{ github.event.inputs.ami_id }}" \
-          -var="instance_type=${{ github.event.inputs.instance_type }}" \
-          -var="subnet_id=${{ github.event.inputs.subnet_id }}" \
-          -var="security_group_id=${{ github.event.inputs.security_group_id }}" \
-          -var="s3_bucket_name=${{ github.event.inputs.s3_bucket_name }}" 
+        case "${{ github.event.inputs.terraform_action }}" in
+          apply)
+            terraform apply -auto-approve \
+              -var="aws_region=${{ github.event.inputs.aws_region }}" \
+              -var="create_ec2=${{ github.event.inputs.create_ec2 }}" \
+              -var="create_s3=${{ github.event.inputs.create_s3 }}" \
+              -var="create_autoscaling=${{ github.event.inputs.create_autoscaling }}" \
+              -var="ami_id=${{ github.event.inputs.ami_id }}" \
+              -var="instance_type=${{ github.event.inputs.instance_type }}" \
+              -var="subnet_id=${{ github.event.inputs.subnet_id }}" \
+              -var="security_group_id=${{ github.event.inputs.security_group_id }}" \
+              -var="s3_bucket_name=${{ github.event.inputs.s3_bucket_name }}"
+            ;;
+          destroy_ec2)
+            terraform destroy -auto-approve \
+              -target=aws_instance.ec2_instance
+            ;;
+          destroy_s3)
+            terraform destroy -auto-approve \
+              -target=aws_s3_bucket.s3_bucket
+            ;;
+          destroy_autoscaling)
+            terraform destroy -auto-approve \
+              -target=aws_autoscaling_group.autoscaling_group
+            ;;
+          destroy_all)
+            terraform destroy -auto-approve
+            ;;
+          *)
+            echo "Invalid terraform_action. Exiting."
+            exit 1
+            ;;
+        esac
